name: example
description: Demonstrates how to use the fl_mlkit_scanning plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fl_mlkit_scanning:
    path: ../
  flutter:
    sdk: flutter
  flutter_waya: ^1.11.1
  permission_handler: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true