name: example
description: Demonstrates how to use the fl_mlkit_scanning plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

  fl_mlkit_scanning:
    path: ../
  flutter:
    sdk: flutter
  flutter_curiosity: ^4.2.1
  flutter_waya: ^4.0.0
  permission_handler: ^10.2.0
  camera: ^0.10.3

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true