name: example
description: Demonstrates how to use the fl_mlkit_scanning plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  camera: ^0.8.1+5
  fl_mlkit_scanning:
    path: ../
  flutter:
    sdk: flutter
  flutter_curiosity: ^3.1.0
  flutter_waya: ^1.11.1
  permission_handler: ^8.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true