name: example
description: Demonstrates how to use the fl_mlkit_identify_language plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_mlkit_identify_language:
    path: ../
  fl_extended: ^1.5.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true