name: fl_mlkit
description: Google mlkit for flutter plugin , supports Android and IOS.
version: 1.0.0
repository: https://github.com/Wayaer/fl_mlkit

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1