name: fl_mlkit_scanning
description: Google mlkit scanning plugin, supports Android and IOS.
version: 0.0.1
repository: https://github.com/Wayaer/fl_mlkit_scanning.git

environment:
  sdk: '>=2.12.1 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  fl_camera:
    git:
      url: git://github.com/Wayaer/fl_camera.git
  flutter:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: fl.mlkit.scanning
        pluginClass: FlMlKitScanningPlugin
      ios:
        pluginClass: FlMlKitScanningPlugin
