name: fl_mlkit_scanning
description: Google mlkit scanning for flutter plugin , supports Android and IOS.
version: 3.0.0
repository: https://github.com/Wayaer/fl_mlkit_scanning.git

environment:
  sdk: '>=2.12.1 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  fl_camera: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: fl.mlkit.scanning
        pluginClass: FlMlKitScanningPlugin
      ios:
        pluginClass: FlMlKitScanningPlugin
