name: example
description: Demonstrates how to use the fl_mlkit_scanning plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: '>=3.16.0'

dependencies:

  fl_mlkit_scanning:
    path: ../
  flutter:
    sdk: flutter
  flutter_curiosity: ^6.0.0
  flutter_waya: ^8.7.2
  permission_handler: ^11.3.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true