name: example
description: Demonstrates how to use the fl_camera plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_camera:
    path: ../
  flutter_curiosity: ^4.5.0
  flutter_waya: ^8.0.3
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true