name: fl_camera
description: A camera plugin for flutter , support Android(used CameraX) and IOS
version: 4.0.0
repository: https://github.com/Wayaer/fl_mlkit/tree/main/fl_camera

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_channel:
    path: ../fl_channel

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: fl.camera
        pluginClass: FlCameraPlugin
      ios:
        pluginClass: FlCameraPlugin