name: fl_camera
description: A camera plugin for flutter , support Android(used CameraX) and IOS
version: 3.1.3
repository: https://github.com/Wayaer/fl_camera.git

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: fl.camera
        pluginClass: FlCameraPlugin
      ios:
        pluginClass: FlCameraPlugin