name: example
description: Demonstrates how to use the fl_mlkit_text_recognize plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: '>=3.16.0'

dependencies:
  fl_mlkit_text_recognize:
    path: ../
  flutter:
    sdk: flutter
  fl_extended: ^1.0.0
  fl_list_wheel: ^0.0.1
  permission_handler: ^11.3.1
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
