name: fl_mlkit_text_recognize
description: Google mlkit text recognize plugin, supports Android and IOS.
version: 3.0.0
repository: https://github.com/Wayaer/fl_mlkit/tree/main/fl_mlkit_text_recognize

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  fl_camera: ^4.0.0
  fl_channel: ^0.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: fl.mlkit.text.recognize
        pluginClass: FlMlKitTextRecognizePlugin
      ios:
        pluginClass: FlMlKitTextRecognizePlugin
