name: fl_mlkit_text_recognize
description: Google mlkit text recognize plugin, supports Android and IOS.
version: 3.2.0
repository: https://github.com/Wayaer/fl_mlkit/tree/main/fl_mlkit_text_recognize

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  fl_channel: ^1.0.2
  fl_camera:
    path: ../fl_camera

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fl.mlkit.text.recognize
        pluginClass: FlMlKitTextRecognizePlugin
      ios:
        pluginClass: FlMlKitTextRecognizePlugin
