name: fl_mlkit_translate_text
description: Google mlkit translate text for flutter plugin , supports Android and IOS.
version: 1.1.3
repository: https://github.com/Wayaer/fl_mlkit/tree/main/fl_mlkit_translate_text

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  plugin:
    platforms:
      android:
        package: fl.mlkit.translate.text
        pluginClass: FlMlKitTranslateTextPlugin
      ios:
        pluginClass: FlMlKitTranslateTextPlugin