name: fl_mlkit_translate_text
description: Google mlkit translate text for flutter plugin , supports Android and IOS.
version: 1.2.1
repository: https://github.com/Wayaer/fl_mlkit/tree/main/fl_mlkit_translate_text

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fl.mlkit.translate.text
        pluginClass: FlMlKitTranslateTextPlugin
      ios:
        pluginClass: FlMlKitTranslateTextPlugin