name: fl_mlkit_identify_language
description: Identify the language of text with ML Kit on Android And IOS
version: 1.2.1
repository: https://github.com/Wayaer/fl_mlkit/tree/main/fl_mlkit_identify_language

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fl.mlkit.identify.language
        pluginClass: FlMlKitIdentifyLanguagePlugin
      ios:
        pluginClass: FlMlKitIdentifyLanguagePlugin