name: fl_mlkit_scanning
description: Google mlkit scanning for flutter plugin , supports Android and IOS.
version: 5.2.0
repository: https://github.com/Wayaer/fl_mlkit/tree/main/fl_mlkit_scanning

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  fl_camera: ^4.2.0
  fl_channel: ^0.2.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fl.mlkit.scanning
        pluginClass: FlMlKitScanningPlugin
      ios:
        pluginClass: FlMlKitScanningPlugin
