name: fl_mlkit_scanning
description: Google mlkit scanning for flutter plugin , supports Android and IOS.
version: 5.0.0
repository: https://github.com/Wayaer/fl_mlkit/tree/main/fl_mlkit_scanning

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  fl_camera:
    path: ../fl_camera
  fl_channel:
    path: ../../fl_channel
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: fl.mlkit.scanning
        pluginClass: FlMlKitScanningPlugin
      ios:
        pluginClass: FlMlKitScanningPlugin
